---
new_page_extension: md
auto_deploy: false
admin_path: "/static/kathi"
webhook_url: 
sections:
- type: directory
  path: content/portfolio
  label: Portfolio
  create: documents
  match: "**/*"
  templates:
  - portfolio
upload_dir: cms
public_path: https://res.cloudinary.com/gazduig/image/upload/f_auto,q_auto:good
front_matter_path: ''
use_front_matter_path: 
file_template: ":filename:"
build:
  preview_output_directory: public
  install_dependencies_command: npm install
  preview_docker_image: forestryio/node:12
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: npm run forestry:preview
